name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
       - name: hello step
         run: |
               echo "welcome to hello world"
               echo "welcome to hello world"
